name: update-gradle-wrapper

on:
  schedule:
    - cron: "0 21 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Update Gradle Wrapper
        uses: rahulsom/gradle-up@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
